theme: jekyll-theme-cayman
title: Euclidean Shortest Path Problem
description: Euclidean Shortest Path for a Circular Moving object in a Plane filled with User Defined Polyhedral Objects


                Anuja Vane, Dhaval Chauhan, Saylee Bhide
